10 UI tesztek
BME-MIT-IET/iet-hf-2024-tappancs-iet pull request #11
Opened 2024-05-19 23:30 UTC by dzsef

Kérlek pillantsatok rá a UI tesztekre, ha van kérdésetek, vagy változtatás igényetek akkor szóljatok, illetve nyugodtan commitolhattok erre a branchre Ti is! :D

2024-05-20 08:41 UTC, Trogbolt approved these changes
Szép munka!

2024-05-20 08:59 UTC, ViolaAndo requested changes
Nagyon szép, igényes munka! Egyedül, amit érdemes lenne kijavítani az az, hogy a pom.xml 18. és 45. sorában szerepel 2-szer ugyanaz a függőség, ami miatt warning-ol is a fordító.

2024-05-20 09:01 UTC, dzsef commented
Köszi az észrevételt, javítom!

2024-05-20 09:04 UTC, Trogbolt commented
Köszi a gyors javítást!

2024-05-20 09:06 UTC, merged

2024-05-22 17:21 UTC, dzsef commented
2aacf0f604c5d30b5e393aebf0d56960a22f91f8 GDrain tests UI tests added, I also changed the intersect method in order to be more readable.

2024-05-22 17:23 UTC, dzsef commented
f4b91d3d552dcc3b4ede25f9c76a912dd09b2daa GMechanic UI tests added, changed the intersect method again, now it uses the sign method and calculates more accurately.

2024-05-22 17:24 UTC, dzsef commented
0e069a924d8ac94ff35f5fded546382283c363ab GPipe UI tests added, also added 2 setters for the tests.

2024-05-22 17:27 UTC, dzsef commented
e38dbf064ebc54baa5d9f3d4c284390102282932  GPump tests added. We test the Intersect function of the pump in more detail. In test 4, we check whether a target coordinate is inside the pump, outside the pump, on the edge or corner of the pump.

2024-05-22 17:27 UTC, dzsef commented
afe6407c288c87dc378fb8ab9505840655f0060c Very similar to the previous one: we test whether a given coordinate is outside, inside or on the edge of the saboteur.

2024-05-22 17:28 UTC, dzsef commented
0abf98eeeccf397f432ad6be74acf8e805d0c4c4 We check whether a given coordinate is outside or inside the source.

2024-05-22 17:29 UTC, dzsef commented
a4f1932497d9575472aae9bb7c2cc1c1d544e6a9 We test that the text fields in the main menu really receive the value entered by the user.

2024-05-22 17:29 UTC, dzsef commented
7c1a1034680e8a7fbfb73607b5ba114836a49a24 and 6c9ebdf0fdbdc45b8bfc2df7a6f8f6c99d897cb3 Refreshing the pom.xml